const Citys = [
  { name: "Ambon" },
  { name: "Aceh" },
  { name: "Balikpapan" },
  { name: "Bandar Lampung" },
  { name: "Bandung" },
  { name: "Banjar" },
  { name: "Banjarbaru" },
  { name: "Banjarmasin" },
  { name: "Batam" },
  { name: "Batu" },
  { name: "Baubau" },
  { name: "Bekasi" },
  { name: "Bengkulu" },
  { name: "Bima" },
  { name: "Binjai" },
  { name: "Bitung" },
  { name: "Blitar" },
  { name: "Bogor" },
  { name: "Bontang" },
  { name: "Bukittinggi" },
  { name: "Cilegon" },
  { name: "Cimahi" },
  { name: "Cirebon" },
  { name: "Denpasar" },
  { name: "Depok" },
  { name: "Dumai" },
  { name: "Gorontalo" },
  { name: "Gunungsitoli" },
  { name: "Jakarta" },
  { name: "Jakarta Barat" },
  { name: "Jakarta Pusat" },
  { name: "Jakarta Selatan" },
  { name: "Jakarta Timur" },
  { name: "Jakarta Utara" },
  { name: "Jambi" },
  { name: "Jayapura" },
  { name: "Kediri" },
  { name: "Kendari" },
  { name: "Kotamobagu" },
  { name: "Kupang" },
  { name: "Langsa" },
  { name: "Lhokseumawe" },
  { name: "Lubuklinggau" },
  { name: "Madiun" },
  { name: "Magelang" },
  { name: "Makassar" },
  { name: "Malang" },
  { name: "Manado" },
  { name: "Mataram" },
  { name: "Medan" },
  { name: "Metro" },
  { name: "Mojokerto" },
  { name: "Padang" },
  { name: "Padang Panjang" },
  { name: "Padang Sidempuan" },
  { name: "Pagar Alam" },
  { name: "Palangka Raya" },
  { name: "Palembang" },
  { name: "Palopo" },
  { name: "Palu" },
  { name: "Pangkalpinang" },
  { name: "Parepare" },
  { name: "Pariaman" },
  { name: "Pasuruan" },
  { name: "Payakumbuh" },
  { name: "Pekalongan" },
  { name: "Pekanbaru" },
  { name: "Pematangsiantar" },
  { name: "Pontianak" },
  { name: "Prabumulih" },
  { name: "Probolinggo" },
  { name: "Sabang" },
  { name: "Salatiga" },
  { name: "Samarinda" },
  { name: "Sawahlunto" },
  { name: "Semarang" },
  { name: "Serang" },
  { name: "Sibolga" },
  { name: "Singkawang" },
  { name: "Solok" },
  { name: "Sorong" },
  { name: "Subulussalam" },
  { name: "Sukabumi" },
  { name: "Sungai Penuh" },
  { name: "Surabaya" },
  { name: "Surakarta" },
  { name: "Tangerang Selatan" },
  { name: "Tangerang" },
  { name: "Tanjungbalai" },
  { name: "Tanjungpinang" },
  { name: "Tarakan" },
  { name: "Tasikmalaya" },
  { name: "Tebing Tinggi" },
  { name: "Tegal" },
  { name: "Ternate" },
  { name: "Tidore Kepulauan" },
  { name: "Tomohon" },
  { name: "Tual" },
  { name: "Yogyakarta" }
];

export default Citys;
