const Citys = [
  { id:1, name: "Ambon" },
  { id:2, name: "Aceh" },
  { id:3, name: "Balikpapan" },
  { id:4, name: "Bandar Lampung" },
  { id:5, name: "Bandung" },
  { id:6, name: "Banjar" },
  { id:7, name: "Banjarbaru" },
  { id:8, name: "Banjarmasin" },
  { id:9, name: "Batam" },
  { id:10, name: "Batu" },
  { id:11, name: "Baubau" },
  { id:12, name: "Bekasi" },
  { id:13, name: "Bengkulu" },
  { id:14, name: "Bima" },
  { id:15, name: "Binjai" },
  { id:16, name: "Bitung" },
  { id:17, name: "Blitar" },
  { id:18, name: "Bogor" },
  { id:19, name: "Bontang" },
  { id:20, name: "Bukittinggi" },
  { id:21, name: "Cilegon" },
  { id:22, name: "Cimahi" },
  { id:23, name: "Cirebon" },
  { id:24, name: "Denpasar" },
  { id:25, name: "Depok" },
  { id:26, name: "Dumai" },
  { id:27, name: "Gorontalo" },
  { id:28, name: "Gunungsitoli" },
  { id:29, name: "Jakarta" },
  { id:30, name: "Jakarta Barat" },
  { id:31, name: "Jakarta Pusat" },
  { id:32, name: "Jakarta Selatan" },
  { id:33, name: "Jakarta Timur" },
  { id:34, name: "Jakarta Utara" },
  { id:35, name: "Jambi" },
  { id:36, name: "Jayapura" },
  { id:37, name: "Kediri" },
  { id:38, name: "Kendari" },
  { id:39, name: "Kotamobagu" },
  { id:40, name: "Kupang" },
  { id:41, name: "Langsa" },
  { id:42, name: "Lhokseumawe" },
  { id:43, name: "Lubuklinggau" },
  { id:44, name: "Madiun" },
  { id:45, name: "Magelang" },
  { id:46, name: "Makassar" },
  { id:47, name: "Malang" },
  { id:48, name: "Manado" },
  { id:49, name: "Mataram" },
  { id:50, name: "Medan" },
  { id:51, name: "Metro" },
  { id:52, name: "Mojokerto" },
  { id:53, name: "Padang" },
  { id:54, name: "Padang Panjang" },
  { id:55, name: "Padang Sidempuan" },
  { id:56, name: "Pagar Alam" },
  { id:57, name: "Palangka Raya" },
  { id:58, name: "Palembang" },
  { id:59, name: "Palopo" },
  { id:60, name: "Palu" },
  { id:61, name: "Pangkalpinang" },
  { id:62, name: "Parepare" },
  { id:63, name: "Pariaman" },
  { id:64, name: "Pasuruan" },
  { id:65, name: "Payakumbuh" },
  { id:66, name: "Pekalongan" },
  { id:67, name: "Pekanbaru" },
  { id:68, name: "Pematangsiantar" },
  { id:69, name: "Pontianak" },
  { id:70, name: "Prabumulih" },
  { id:71, name: "Probolinggo" },
  { id:72, name: "Sabang" },
  { id:73, name: "Salatiga" },
  { id:74, name: "Samarinda" },
  { id:75, name: "Sawahlunto" },
  { id:76, name: "Semarang" },
  { id:77, name: "Serang" },
  { id:78, name: "Sibolga" },
  { id:79, name: "Singkawang" },
  { id:80, name: "Solok" },
  { id:81, name: "Sorong" },
  { id:82, name: "Subulussalam" },
  { id:83, name: "Sukabumi" },
  { id:84, name: "Sungai Penuh" },
  { id:85, name: "Surabaya" },
  { id:86, name: "Surakarta" },
  { id:87, name: "Tangerang Selatan" },
  { id:88, name: "Tangerang" },
  { id:89, name: "Tanjungbalai" },
  { id:90, name: "Tanjungpinang" },
  { id:91, name: "Tarakan" },
  { id:92, name: "Tasikmalaya" },
  { id:93, name: "Tebing Tinggi" },
  { id:94, name: "Tegal" },
  { id:95, name: "Ternate" },
  { id:96, name: "Tidore Kepulauan" },
  { id:97, name: "Tomohon" },
  { id:98, name: "Tual" },
  { id:99, name: "Yogyakarta" }
];

export default Citys;
